version: '3.4'

services:

  postgresql_db:
    image: postgres:latest
   
  mongo-reports:
    image: mongo

  rabbitMQ:
    image: rabbitmq:3-management

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    

  contactsapi:
    image: ${DOCKER_REGISTRY-}contactsapi

  reportsapi:
    image: ${DOCKER_REGISTRY-}reportsapi
    build:
      context: .
      dockerfile: Services/Reports/ReportsAPI/Dockerfile

volumes:
  postgres-volume:
    name: postgres-volume
    external: false
  mongo-reports-volume:
   name: mongo-reports-volume
   external: false
  mongo-reports-volume-config:
   name: mongo-reports-volume-config
   external: false
  rabbitmq-volume:
   name: rabbitmq-volume
   external: false
