version: '3.4'

services:

  postgresql_db:
    image: postgres:latest
    

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    

  contactsapi:
    image: ${DOCKER_REGISTRY-}contactsapi
    build:
      context: .
      dockerfile: Services/Contacts/ContactsAPI/Dockerfile
    ports:
      - "8080:80"

volumes:
  postgres-volume:
    name: postgres-volume
    external: false