version: '3.4'

services:

  postgresql_db:
    image: postgres:latest
   
  mongo-reports:
    image: mongo

  rabbitMQ:
    image: rabbitmq:3-management

  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    

  contactsapi:
    image: ${DOCKER_REGISTRY-}contactsapi
    build:
      context: .
      dockerfile: Services/Contacts/ContactsAPI/Dockerfile
    ports:
      - "8080:80"
      - "56849:443"

volumes:
  postgres-volume:
    name: postgres-volume
    external: false
  mongo-reports-volume:
   name: mongo-reports-volume
   external: false
  rabbitmq-volume:
   name: rabbitmq-volume
   external: false