version: '3.4'

services:
  postgresql_db:
    container_name: postgresql_db
    restart: always
    environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: azx@1234
     POSTGRES_DB: postgres
    volumes:
     - postgres-volume:/var/lib/postgresql/data
    ports:
     - "5432:5432"

  mongo-reports:
    container_name: mongo-reports
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: azx1234
    volumes:
     - mongo-reports-volume:/data/db
     - mongo-reports-volume:/data/config/db
    ports:
     - "27017:27017"

  rabbitMQ:
    container_name: rabbitMQ
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  apigateway:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
     - "8000:80"

  contactsapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

